name: Build Docker Image
on:
  push:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-docker-hub:
    name: Build it!
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build vue-app
        run: |
          ./build.sh react-app
          # docker build -t "$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA}" .
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 'nazt/xxz'
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
